server:
  port: 8020
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/ErickIMT/ProyectoWebTestIntegraciones.git
          searchPaths: ConfigData
          username: erickisrael203@gmail.com
          password: 8620152Erick
  security:
    user:
      name: root
      password: 3r1ck