spring:
  application:
    name: comercio-service
  config:
    import: configserver:http://localhost:8020
  cloud:
    config:
      uri: http://localhot:8020
      username: root
      password: 3r1ck